# Generated by Django 4.1.9 on 2026-08-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True)),
                ("asked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-asked_at"],},
        ),
    ]
