# Generated by Django 4.1.9 on 2026-08-15 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="receipts/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("merchant", models.CharField(blank=True, max_length=200)),
                ("bought_at", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("item_count", models.IntegerField(default=0)),
                ("most_expensive_item", models.CharField(blank=True, max_length=200)),
                ("top_category", models.CharField(blank=True, max_length=50)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
            ],
            options={"ordering": ["-uploaded_at"],},
        ),
        migrations.CreateModel(
            name="ReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="receipts.receipt",
                    ),
                ),
            ],
            options={"ordering": ["id"],},
        ),
    ]
