# Generated by Django 4.1.9 on 2026-08-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="receipt", name="image",),
    ]
