# Generated by Django 4.1.9 on 2026-08-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0002_remove_receipt_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="receipt",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="receipt",
            name="service_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="receipt",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="receipt",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
